title: "Kaitlin Karl / Homepage"
description: "personal description"
url: "https://kaitmkarl.github.io"
baseurl: ""
theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
