# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Kaitlin Karl / Homepage"
title_separator          : "-"
name                     : &name "Kaitlin M. Karl"
description              : &description "personal description"
url                      : https://kaitmkarl.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io" or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "kaitmkarl.github.io"

title: "Kaitlin Karl / Homepage"
description: "personal description"
url: "https://kaitmkarl.github.io"
baseurl: ""
theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
